"""add user_setting table

Revision ID: 0a6628028d28
Revises: 5fb34efae4d6
Create Date: 2026-08-05 16:33:37.785079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a6628028d28'
down_revision: Union[str, Sequence[str], None] = '5fb34efae4d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_setting',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('focus_duration', sa.Integer(), nullable=False),
    sa.Column('short_break_duration', sa.Integer(), nullable=False),
    sa.Column('long_break_duration', sa.Integer(), nullable=False),
    sa.Column('blocks_per_cycle', sa.Integer(), nullable=False),
    sa.Column('auto_start_breaks', sa.Boolean(), nullable=False),
    sa.Column('auto_start_next', sa.Boolean(), nullable=False),
    sa.Column('sound', sa.Boolean(), nullable=False),
    sa.Column('notifications', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_setting_user_id'), 'user_setting', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_setting_user_id'), table_name='user_setting')
    op.drop_table('user_setting')
    # ### end Alembic commands ###
