"""remove redundant ix_block_user_id index

Revision ID: 41457faa8aa7
Revises: 0a6628028d28
Create Date: 2026-08-05 17:34:59.312928

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '41457faa8aa7'
down_revision: str | Sequence[str] | None = '0a6628028d28'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_block_user_id'), table_name='block')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_block_user_id'), 'block', ['user_id'], unique=False)
    # ### end Alembic commands ###
