"""add block and block_interval tables

Revision ID: 5fb34efae4d6
Revises: ea94268241a7
Create Date: 2026-08-05 16:09:05.933225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb34efae4d6'
down_revision: Union[str, Sequence[str], None] = 'ea94268241a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('completed', 'aborted', name='block_status'), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_started_at'), 'block', ['started_at'], unique=False)
    op.create_index(op.f('ix_block_tag_id'), 'block', ['tag_id'], unique=False)
    op.create_index(op.f('ix_block_user_id'), 'block', ['user_id'], unique=False)
    op.create_index('ix_block_user_id_started_at', 'block', ['user_id', 'started_at'], unique=False)
    op.create_table('block_interval',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('block_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['block.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_interval_block_id'), 'block_interval', ['block_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_block_interval_block_id'), table_name='block_interval')
    op.drop_table('block_interval')
    op.drop_index('ix_block_user_id_started_at', table_name='block')
    op.drop_index(op.f('ix_block_user_id'), table_name='block')
    op.drop_index(op.f('ix_block_tag_id'), table_name='block')
    op.drop_index(op.f('ix_block_started_at'), table_name='block')
    op.drop_table('block')
    # ### end Alembic commands ###
