"""add unique constraint on tag (user_id, name)

Revision ID: c6a6c45f608d
Revises: 41457faa8aa7
Create Date: 2026-08-05 17:59:51.667783

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c6a6c45f608d'
down_revision: str | Sequence[str] | None = '41457faa8aa7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_tag_user_name', 'tag', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tag_user_name', 'tag', type_='unique')
    # ### end Alembic commands ###
